name: Check Schemas

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-schemas:
    runs-on: ${{ vars.RUNNER_TYPE }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6
        with:
          python-version: '3.x'
      - name: Install jsonschema
        run: pip install jsonschema
      - name: Run check_schemas.py
        run: |
          python tools/check_schemas.py
